---
{{- if not .Values.localHelmValues.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-forge
  namespace: argocd
spec:
  project: default
{{- if .Values.externalValues.enabled }}
  # helm-chart & values file from 2 different git repos
  # Uses the SAME targetRevision for both chart templates AND values
  sources:
  - repoURL: {{ .Values.clusterForge.repoUrl }}
    targetRevision: {{ .Values.clusterForge.targetRevision }}
    path: root
    helm:
      valueFiles:
        - {{ .Values.externalValues.path }}
        {{- if .Values.global.clusterSize }}
        - {{ .Values.global.clusterSize }}
        {{- end }}
        - $cluster-values/values.yaml
  - repoURL: {{ .Values.externalValues.repoUrl }}
    targetRevision: {{ .Values.externalValues.targetRevision }}
    ref: cluster-values
{{- else }}
  # helm-chart & values file within the same git repo
  source:
    repoURL: {{ .Values.clusterForge.repoUrl }}
    targetRevision: {{ .Values.clusterForge.targetRevision }}
    path: root
    helm:
      {{- if .Values.clusterForge.targetRevision }}
      parameters:
        - name: clusterForge.targetRevision
          value: {{ .Values.clusterForge.targetRevision | quote }}
      {{- end }}
      valueFiles:
        - {{ .Values.clusterForge.valuesFile }}
        {{- if .Values.global.clusterSize }}
        - {{ .Values.global.clusterSize }}
        {{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}