apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: openstack-gateway-params
  namespace: kgateway-system
spec:
  kube:
    service:
      annotations:
        loadbalancer.openstack.org/floating-ip: "{{ .Values.loadBalancerIP }}"
